package com.recoder.stockledger

object StockLedgerPreferences {
    const val PREFERENCES_NAME = "stock_ledger_preferences"
    const val KEY_DISPLAY_CURRENCY = "display_currency"
    const val KEY_SELECTED_PLATFORM = "selected_platform"
    const val KEY_ENABLED_PLATFORMS = "enabled_platforms"
    const val KEY_PLATFORM_FEE_PLAN_SELECTIONS = "platform_fee_plan_selections"
    const val KEY_ZHUORUI_EMAIL_AUTO_IMPORT_ENABLED = "zhuorui_email_auto_import_enabled"
    const val KEY_ZHUORUI_EMAIL_IMAP_HOST = "zhuorui_email_imap_host"
    const val KEY_ZHUORUI_EMAIL_IMAP_PORT = "zhuorui_email_imap_port"
    const val KEY_ZHUORUI_EMAIL_ACCOUNT = "zhuorui_email_account"
    const val KEY_ZHUORUI_EMAIL_PASSWORD = "zhuorui_email_password"
    const val KEY_ZHUORUI_EMAIL_FOLDER = "zhuorui_email_folder"
    const val KEY_ZHUORUI_EMAIL_LAST_SYNC_AT = "zhuorui_email_last_sync_at"
    const val KEY_ZHUORUI_EMAIL_LAST_SYNC_MESSAGE = "zhuorui_email_last_sync_message"
    const val KEY_ZHUORUI_PROMO_START_DATE = "zhuorui_promo_start_date"
    const val KEY_ZHUORUI_PROMO_DURATION_DAYS = "zhuorui_promo_duration_days"
    const val KEY_ZHUORUI_STATEMENT_PDF_PASSWORD = "zhuorui_statement_pdf_password"
    const val KEY_OPENAI_API_KEY = "openai_api_key"
    const val KEY_ALIBABA_BAILIAN_API_KEY = "alibaba_bailian_api_key"
    const val KEY_VISION_IMPORT_MODEL = "vision_import_model"
    const val KEY_VISION_API_BASE_URL = "vision_api_base_url"
    const val KEY_ZHUORUI_PDF_IMPORT_MODE = "zhuorui_pdf_import_mode"
    const val KEY_TEXT_IMPORT_MODEL = "text_import_model"
}
